### ISSUE TITLE
First failure is not captured by Silent Retry

### ISSUE THREAD

**Issue by mentz** [trusted/sidekiq-silent-retry#6]
Hello! Love the gem.

I am facing an issue where, seemingly, the first time a silenced error occurs on a given Sidekiq job, it causes an error to be raised by the gem itself as it tries to check for a value that is not available -- the `job_payload['retry_count']`.

Sidekiq shows that a nil value is used in a comparison:
<img width="699" alt="image" src="https://github.com/user-attachments/assets/4904e9a7-ee02-4e28-9ff2-41deb9e57d04">

I've added a breakpoint where the error happens, and looked at the contents of `job_payload` on the first and on the second retries. I added `debugger` before line 20 on this file:
https://github.com/trusted/sidekiq-silent-retry/blob/e7dcdb2d296578343133d7b0fbbad703206d7786/lib/sidekiq/silent_retry/server_middleware.rb#L19-L21

```ruby
# 1st time the job failed by a silenced error
==> job_payload
{"retry"=>3,
 "queue"=>"my_queue",
 "retry_in"=>300,
 "silent_retry"=>["SilencedError"],
 "args"=>["redacted"],
 "class"=>"MyJob",
 "jid"=>"redacted",
 "created_at"=>1723749896.382946,
 "bid"=>"redacted",
 "enqueued_at"=>1723749896.383102}
==> continue
# then the method fails with a "NoMethodError: undefined method `>=' for nil:NilClass" error
# which triggers the alerts on my application since it's an unexpected error.

# 2nd time the job failed, when it is retried by Sidekiq for the 1st failure
==> job_payload
{"retry"=>3,
 "queue"=>"my_queue",
 "retry_in"=>300,
 "silent_retry"=>["SilencedError"],
 "args"=>["redacted"],
 "class"=>"MyJob",
 "jid"=>"redacted",
 "created_at"=>1723749896.382946,
 "bid"=>"redacted",
 "enqueued_at"=>1723750427.9472692,
 "error_message"=>"undefined method `>=' for nil:NilClass",  # new
 "error_class"=>"NoMethodError",                             # new
 "failed_at"=>1723750118.844531,                             # new
 "retry_count"=>0}                                           # new
==> continue
# this time around the method continues normally and raises the MySilentRetryError error
# without triggering any alerts, as I expect it to.
```

**Comment by kammradt** [comment]
Faced the same issue

I'm able to help if needed!
